### ISSUE TITLE
MacOS Issues during Deployment 

### ISSUE THREAD

**Issue by simonr3** [corda/corda-kubernetes-deployment#22]
Corda Node, Bridge, Float in k8s deployment now up and running and connected to CENM k8s deployment AND have done end to end transaction. Issues raised:

1) Document that Public IP's SKU's need to configured as Standard and not Basic when setting up the Public IP Addresses or else this error occurs:

  Normal   EnsuringLoadBalancer        5s (x5 over 82s)  service-controller    Ensuring load balancer
  Warning  CreateOrUpdateLoadBalancer  4s (x5 over 81s)  azure-cloud-provider  Code="PublicIPAndLBSkuDoNotMatch" Message="Standard sku load balancer /subscriptions/af4f0732-dd8c-4330-a357-b9593255c3f0/resourceGroups/mc_sjw-k8s-bridge_sjwaksclusterbridge_eastus2/providers/Microsoft.Network/loadBalancers/kubernetes cannot reference Basic sku publicIP /subscriptions/af4f0732-dd8c-4330-a357-b9593255c3f0/resourceGroups/MC_sjw-k8s-bridge_sjwAKSClusterBridge_eastus2/providers/Microsoft.Network/publicIPAddresses/floatLBIP." Details=[]
  Warning  SyncLoadBalancerFailed      4s (x5 over 81s)  service-controller    Error syncing load balancer: failed to ensure load balancer: timed out waiting for the condition

2) Fix issue with Artifactory downloads not working, right now Corda Software Binaries need to be manually copied from Artifactory to : corda-kubernetes-deployment/docker-images/bin

3) Don't remove the network-root-truststore.jks file when user runs reset_environment.sh, this file should remain there to make users life easier doing a reset. 

4) Please advised on any fixes that were made to the shell scripts to address the "readlink" issue which caused a lot of scripts to break from Windows to Mac.

**Comment by henrikr3** [comment]
Thanks for the feedback Simon.
I can clarify the documentation around Public IP's used for Azure, this is Azure specific issue and not related to the deployment, but it is worth noting in the documentation, at least in the SETUP_CHECKLIST.md file.

Regarding the following issues reported:
2) I think wget needs to be installed in order to use download_binaries.sh on macOS. Will add some improvement.
3) The reset_environment.sh file does not remove the *.jks file under helm/files/network, this has always been the case
4) I'm not sure what the ask is for this one. There should not be any issues regarding readlink on macOS any longer.

**Comment by henrikr3** [comment]
Thanks for the detailed issues report Simon. The issues mentioned have now all been fixed in recent commits.
